name: tech_challenge_flutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  loader_overlay: ^5.0.0
  flutter_slidable: ^4.0.0
  flutter_native_splash: ^2.2.16
  provider: ^6.1.5
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_app_check: ^0.3.2+10
  intl: ^0.19.0
  uuid: ^4.5.1
  path: ^1.9.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.1.0
  image_gallery_saver_plus: ^4.0.1
  dio: ^5.4.0
  permission_handler: ^11.0.0
  fl_chart: ^0.66.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  image: assets/icon/icon.png
  color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 700
